# Generated by Django 3.0.8 on 2020-08-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='business_potential',
            new_name='Business_Potential',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='company_size',
            new_name='Company_Size',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='lead_source',
            new_name='Lead_Source',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='lead_type',
            new_name='Lead_Type',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='lead_priority',
            new_name='Leads_Priority',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='marketplace_subsource',
            new_name='Market_Place_Subsource',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='month',
            new_name='Month',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='platform',
            new_name='Platform',
        ),
    ]
